APPLY_FIXES: all
DISABLE_LINTERS:
  - JSON_JSONLINT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
FAIL_IF_UPDATED_SOURCES: true
GITHUB_STATUS_REPORTER: true
REPOSITORY_KICS_ARGUMENTS: --fail-on critical,high
PYTHON_DEFAULT_STYLE: ruff
REPOSITORY_SEMGREP_RULESETS: [p/default]
SARIF_REPORTER: true
VALIDATE_ALL_CODEBASE: false
