services:
  app_dev:
    image: ghcr.io/yxtay/python-example-app:dev
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
      cache_to:
        - type=inline
      target: dev
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/opt/app
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost/']
    cap_drop:
      - all
    security_opt:
      - apparmor:unconfined
    profiles:
      - dev
  app_ci:
    image: ghcr.io/yxtay/python-example-app:ci
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
      cache_to:
        - type=inline
      target: ci
    ports:
      - 127.0.0.1:8000:8000
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost/']
    cap_drop:
      - all
    security_opt:
      - apparmor:unconfined
    profiles:
      - ci
  app:
    image: ghcr.io/yxtay/python-example-app:main
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
        - ghcr.io/yxtay/python-example-app:main
      target: prod
    ports:
      - 127.0.0.1:8000:8000
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost/']
    cap_drop:
      - all
    security_opt:
      - apparmor:unconfined
    profiles:
      - prod
