# kics-scan disable=451d79dc-0588-476a-ad03-3c7f0320abb3,698ed579-b239-4f8f-a388-baa4bcb13ef8
services:
  app_dev:
    image: ghcr.io/yxtay/python-example-app:dev
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
      cache_to:
        - type=inline
      target: dev
    ports:
      - 8000:8000
    volumes:
      - .:/work/app
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    profiles:
      - dev
  app_ci:
    image: ghcr.io/yxtay/python-example-app:ci
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
      cache_to:
        - type=inline
      target: ci
    ports:
      - 8000:8000
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    profiles:
      - ci
  app:
    image: ghcr.io/yxtay/python-example-app:main
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
        - ghcr.io/yxtay/python-example-app:main
      target: prod
    ports:
      - 8000:8000
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    profiles:
      - prod
