services:
  app_dev:
    image: ghcr.io/yxtay/python-example-app:dev
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
      cache_to:
        - type=inline
      target: dev
    healthcheck:
      test: curl -f http://localhost/ || exit 1
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/opt/app
    profiles:
      - dev
  app_ci:
    image: ghcr.io/yxtay/python-example-app:ci
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
      cache_to:
        - type=inline
      target: ci
    healthcheck:
      test: curl -f http://localhost/ || exit 1
    ports:
      - "127.0.0.1:8000:8000"
    profiles:
      - ci
  app:
    image: ghcr.io/yxtay/python-example-app:main
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - ghcr.io/yxtay/python-example-app:dev
        - ghcr.io/yxtay/python-example-app:ci
        - ghcr.io/yxtay/python-example-app:main
      target: prod
    healthcheck:
      test: curl -f http://localhost/ || exit 1
    ports:
      - "127.0.0.1:8000:8000"
    profiles:
      - prod
